function sentimentScores = analyzeSentiment(text, keywords)
    % Inicializa los scores
    sentimentScores = zeros(length(keywords), 1);
    
    % Define palabras de negación
    negationWords = {'no', 'nunca', 'jamás', 'sin embargo', 'aunque', 'a pesar de', 'pero', 'sin embargo'};
    
    % Divide el texto en segmentos (oraciones)
    segments = split(text, '.'); % Separar por oraciones
    for i = 1:length(keywords)
        keyword = keywords{i};
        for j = 1:length(segments)
            if contains(segments{j}, keyword)
                % Verificar si la oración contiene palabras de negación antes de la palabra clave
                isNegated = checkNegation(segments{j}, negationWords);
                
                % Evaluar el sentimiento de la frase
                sentiment = evaluateSentiment(segments{j}, keyword, isNegated); % Función que evalúa el sentimiento con posible negación
                
                % Imprimir la frase y el sentimiento
                fprintf('Frase: "%s"\n', strtrim(segments{j})); % Muestra la frase
                fprintf('Palabra clave: "%s" - Sentimiento asignado: %.2f\n', keyword, sentiment); % Muestra sentimiento

                % Mostrar las negaciones encontradas
                negationsFound = findNegations(segments{j}, negationWords);
                if ~isempty(negationsFound)
                    fprintf('Negaciones encontradas: %s\n', strjoin(negationsFound, ', '));
                end

                % Acumula el sentimiento
                sentimentScores(i) = sentimentScores(i) + sentiment; 
            end
        end
    end
    % Normaliza los scores para que estén en la escala de Saaty
    sentimentScores = normalizeSentimentScores(sentimentScores);
end

function sentiment = evaluateSentiment(segment, keyword, isNegated)
    % Aquí podrías implementar tu lógica de análisis de sentimiento
    % Ejemplo simple: contar palabras positivas/negativas
    veryPositiveWords = {'excelente', 'fantástico', 'maravilloso', 'beneficioso', 'prometedor', ...
                    'exitoso', 'notable', 'superior', 'efectivo', 'facilitar', ...
                    'contribuye', 'lograr', 'avanza', 'impacto', 'reducir', ...
                    'ayudará', 'incluir', 'objetivo', 'fijó', 'mejorar', ...
                    'contribuir', 'alcanzar', 'iniciativa','avance'};

    positiveWords = {'bueno', 'positivo', 'satisfactorio', 'agradable', 'interesante', ...
                 'recomendable', 'útil', 'eficiente', 'reducción', 'aumento', ...
                 'liderazgo', 'clave', 'éxito', 'sostenibilidad', 'celebración', ...
                 'potencia', 'tecnología avanzada', 'mejora', 'impacto positivo', ...
                 'progreso', 'eficiencia', 'proyección', 'compromiso', ...
                 'incentivos', 'promover', 'fomentar'};

    neutralWords = {'neutro', 'regular', 'incluyó', 'fijó'};

    negativeWords = {'malo', 'pobre', 'problemático', 'deficiente', 'insatisfactorio', ...
                 'inútil', 'ineficiente', 'desalentador', 'conflictivo', ...
                 'falta', 'cuestionar', 'dependencia', 'incertidumbre', ...
                 'obstáculo'};

    veryNegativeWords = {'desastroso', 'fallido', 'perjudicial', 'frustrante', 'complejo'};

    sentiment = 0; % Inicializa el sentimiento
    positiveFound = {}; % Lista de palabras positivas encontradas
    negativeFound = {}; % Lista de palabras negativas encontradas

    % Contar palabras
    for pw = veryPositiveWords
        countPositive = count(segment, pw{1});
        if countPositive > 0
            positiveFound{end+1} = pw{1}; % Guarda palabra positiva
        end
        sentiment = sentiment + countPositive * 3; % Aumenta más si hay palabras muy positivas
    end
    
    for pw = positiveWords
        countPositive = count(segment, pw{1});
        if countPositive > 0
            positiveFound{end+1} = pw{1}; % Guarda palabra positiva
        end
        sentiment = sentiment + countPositive * 2; % Aumenta si hay palabras positivas
    end

    for nw = negativeWords
        countNegative = count(segment, nw{1});
        if countNegative > 0
            negativeFound{end+1} = nw{1}; % Guarda palabra negativa
        end
        sentiment = sentiment - countNegative; % Disminuye si hay palabras negativas
    end

    for nw = veryNegativeWords
        countNegative = count(segment, nw{1});
        if countNegative > 0
            negativeFound{end+1} = nw{1}; % Guarda palabra negativa
        end
        sentiment = sentiment - countNegative * 2; % Disminuye más si hay palabras muy negativas
    end

    % Si la oración contiene una negación, invierte el sentimiento
    if isNegated
        sentiment = -sentiment;
    end

    % Mostrar las palabras positivas y negativas encontradas
    if ~isempty(positiveFound)
        fprintf('Palabras positivas encontradas: %s\n', strjoin(positiveFound, ', '));
    end
    if ~isempty(negativeFound)
        fprintf('Palabras negativas encontradas: %s\n', strjoin(negativeFound, ', '));
    end

    % Asigna un valor basado en el conteo
    if sentiment > 0
        sentiment = 3 + (sentiment / 10) * 6; % Convierte a 3-9
    elseif sentiment < 0
        sentiment = 1 + (abs(sentiment) / 10) * 2; % Convierte a 1-3
    else
        sentiment = 5; % Neutral
    end
end

function isNegated = checkNegation(segment, negationWords)
    % Verifica si alguna palabra de negación aparece antes de la palabra clave en la misma oración
    isNegated = false;
    for nw = negationWords
        if contains(segment, nw{1})
            isNegated = true; % La oración está negada
            break;
        end
    end
end

function negationsFound = findNegations(segment, negationWords)
    % Encuentra todas las palabras de negación en la oración
    negationsFound = {};
    for nw = negationWords
        if contains(segment, nw{1})
            negationsFound{end+1} = nw{1};
        end
    end
end

function normalizedScores = normalizeSentimentScores(scores)
    % Normaliza los scores a la escala de Saaty
    maxScore = max(scores);
    normalizedScores = scores / maxScore * 9; % Escala de 1-9
end


% Paso 3: Ejemplo de uso
text = ['En 2018, Chile lanzó su Estrategia Nacional de Electromovilidad para reducir combustibles fósiles y ', ...
         'aumentar vehículos eléctricos. Incluyó buses eléctricos en el transporte público y fijó la meta de ', ...
         'que el 40% de los vehículos sean eléctricos para 2050, aunque aún faltan incentivos fiscales para ', ...
         'autos particulares. Entre 2018 y 2019, Chile experimentó un aumento del 68% en vehículos eléctricos, ', ...
         'liderando en la región. Copec Voltex amplió la red de carga con más de 150 puntos rápidos. La ', ...
         'electromovilidad es clave en el objetivo de Chile de lograr la carbono neutralidad para 2050. ', ...
         'Chile se prepara para la masificación de la electromovilidad con la Ruta Energética 2018-2022, ', ...
         'que proyecta 40% de vehículos eléctricos particulares y 100% de transporte público para 2050. Se ', ...
         'están desarrollando normas de carga y una ley de Eficiencia Energética para incentivar su adopción. ', ...
         'Chile celebra 5 años de electromovilidad con más de 2,240 buses eléctricos, principalmente en Santiago. ', ...
         'Con una proyección de ventas exclusivas de autos eléctricos livianos y medianos para 2035, el país busca ', ...
         'incrementar su flota con 1,200 autobuses adicionales. La feria Fidelmov, celebrada en agosto de 2019, ', ...
         'buscó posicionar a Chile como potencia regional en electromovilidad. Presentó avances en transporte ', ...
         'y formación de capital humano, con la participación de figuras del gobierno y la industria, coincidiendo ', ...
         'con los compromisos de la COP25. MG Motor lanzó su SUV eléctrico MG ZS EV en Chile a finales de 2019. ', ...
         'El modelo, con autonomía de hasta 428 km, busca facilitar la transición hacia vehículos eléctricos con ', ...
         'precios accesibles y tecnología avanzada, respaldado por una alianza con Copec Voltex para soluciones de ', ...
         'carga en hogares. El transporte público eléctrico en Santiago redujo en un 44% la contaminación acústica ', ...
         'en la Alameda entre 2019 y 2023. Se destacó el aumento de buses eléctricos en la flota del sistema Red, ', ...
         'pasando del 12% al 36%. Santiago es una de las ciudades con más buses eléctricos a nivel global, solo ', ...
         'superada por ciudades chinas. En 2022, Foton acordó enviar 1,022 autobuses eléctricos a Chile, ', ...
         'consolidándose como un proveedor clave para el transporte público eléctrico en Santiago. Este es el mayor ', ...
         'pedido extranjero de buses eléctricos para Foton, que ya cuenta con más de 300 unidades operando en el país. ', ...
         'Este avance es parte de los planes para que todo el transporte público chileno sea eléctrico en 2040. ', ...
         'Chile busca prohibir la venta de vehículos a combustión para 2035, aunque algunos sectores cuestionan si ', ...
         'es viable. El país cuenta con 1,414 puntos de carga, principalmente en la Región Metropolitana. El gobierno ', ...
         'sigue comprometido con la meta, afirmando que hay infraestructura suficiente desde Arica hasta Punta Arenas, ', ...
         'destacándose entre los líderes mundiales en disponibilidad de carga. El 15 de octubre de 2021, el gobierno ', ...
         'chileno presentó su Estrategia Nacional de Electromovilidad, con el objetivo de que, para 2035, el 100% de ', ...
         'los vehículos vendidos en el país sean cero emisiones. Esta estrategia incluye el envío al Congreso de un ', ...
         'Proyecto de Ley de Transición Energética, que cubre temas de electromovilidad, hidrógeno verde y energías ', ...
         'renovables. El plan incluye metas específicas para 2035, 2040 y 2045 en transporte y maquinaria, y propone ', ...
         'incentivos como rebajas en el permiso de circulación de vehículos eléctricos. El 6 de abril de 2021, el ', ...
         'gobierno chileno firmó un acuerdo público-privado con 68 empresas para fomentar la electromovilidad y ', ...
         'reducir las emisiones de gases de efecto invernadero. El transporte representa el 36% del consumo energético ', ...
         'en Chile, mayormente dependiente de fuentes fósiles. El acuerdo busca que la electromovilidad contribuya al ', ...
         '20% de la reducción de emisiones necesaria para alcanzar la carbono neutralidad en 2050. Se destacan avances ', ...
         'en corredores eléctricos y buses eléctricos, con metas para 2021, como duplicar modelos de vehículos eléctricos ', ...
         'y aumentar la cantidad de cargadores públicos. En 2023, las ventas de vehículos electrificados en Chile ', ...
         'crecieron un 35%, con 9,336 unidades vendidas. Los híbridos convencionales tuvieron un incremento del ', ...
         '47.6%, mientras que las ventas de vehículos 100% eléctricos aumentaron un 22.6%. El segmento de SUVs ', ...
         'dominó las preferencias, siendo las flotas comerciales responsables de muchas de las ventas de autos eléctricos. ', ...
         'Las ventas de híbridos enchufables y vehículos eléctricos de rango extendido también experimentaron un crecimiento. ', ...
         'Además, se registraron tres prototipos de vehículos impulsados por hidrógeno. En julio de 2023, Chile alcanzó ', ...
         'más de 2,000 buses eléctricos en su sistema de transporte público RED en Santiago, lo que representa el 31% ', ...
         'de la flota total. Se han instalado 23 electroterminales, que contribuyen a mejorar la operación de los buses ', ...
         'eléctricos, reduciendo la contaminación acústica y ambiental. Se espera que, en un futuro cercano, 2 de ', ...
         'cada 3 buses sean eléctricos o Euro VI, en un esfuerzo por mejorar la calidad de vida en la ciudad. Un año ', ...
         'después de la aprobación de la Ley de Eficiencia Energética en Chile, se subraya la necesidad de promover el ', ...
         'uso eficiente de la energía para lograr la transición hacia una economía más sostenible. La ley busca aumentar ', ...
         'la competitividad de las empresas y la seguridad del suministro, y apoya la adopción de tecnologías limpias. ', ...
         'La Asociación de Municipalidades de Chile ha destacado el impacto positivo de la electrificación del transporte ', ...
         'en la reducción de emisiones y costos operativos. Con la implementación de la Ley de Eficiencia Energética, ', ...
         'se busca estimular inversiones en proyectos de energías renovables, lo que ayudará a reducir la dependencia de ', ...
         'combustibles fósiles y mitigar el cambio climático. En resumen, Chile avanza hacia una transición energética y ', ...
         'electromovilidad, buscando liderar la reducción de emisiones y mejorar la calidad de vida de sus ciudadanos.'];
     
keywords = {'incentivo', 'fiscal', 'descuento', 'subsidio', 'bonificación', 'ayuda', ...
    'reducción de impuestos','costo','ahorro', 'apoyo económico', 'beneficio tributario', ...
    'reembolso', 'exoneración', 'política fiscal', 'crédito', 'rebaja', ...
    'financiación', 'deducción','infraestructura', 'estación', 'carga', 'punto de carga', 'red de carga', ...
    'estación de carga', 'disponibilidad', 'cargador', 'electrolinera', ...
    'plataforma de carga', 'terminal de carga', 'punto eléctrico', ...
    'facilidad de acceso', 'recarga', 'capacidad de carga','vehículo', 'eléctrico', 'promover', 'adopción', 'uso', 'fomento', ...
    'conducir', 'atractivo', 'impulsar', 'motivación', 'preferencia', ...
    'transición vehicular', 'conversión', 'demanda', 'incentivar', ...
    'popularización','electromovilidad', 'movilidad', 'promoción', 'transición', 'sostenible', ...
    'vehículos eléctricos', 'soluciones de movilidad', 'conciencia', ...
    'difusión', 'información', 'campaña', 'educación ciudadana', ...
    'evento', 'demostración pública', 'fomento de movilidad verde'
};
 

% Análisis de sentimiento
sentimentScores = analyzeSentiment(text, keywords);

% Mostrar resultados finales
disp('Scores de Sentimiento Normalizados:');
disp(sentimentScores);

